### ISSUE TITLE
Windows: incorrect rotated file birthtime

### ISSUE THREAD

**Issue by cumajkeee** [Rcomian/bunyan-rotating-file-stream#5] opened 2016-05-27 11:52 UTC
On win, rotated files have same birthtime as initial one.
``` javascript
var logs = fs.readdirSync(PATH_TO_LOG_DIR);
logs.forEach(log) {
  var stats = fs.statSync(log);
  console.log(stats.birthtime);
}
```

**Comment by Rcomian** [comment] 2016-05-27 12:00
I'm not sure what the problem is, can you say what you'd expect to see vs what you actually see.

When a file is rotated it is just renamed, so information like the creation date probably won't be affected.

**Comment by cumajkeee** [comment] 2016-05-27 12:13
I use rotation by filesize and max log files as 5. Actually I want to get real birthtime of each log file, instead all files are with birthtime that the first one have.

**Comment by cumajkeee** [comment] 2016-05-27 12:19
Yes rotated file should only be renamed. But new one created had to have different birthtime that previous one.

**Comment by Rcomian** [comment] 2016-05-27 12:23
Ah interesting. ok, I'll take look see if something is being reused that shouldn't be.

is strange tho, creation dates are definitely not being set explicitly.

**Comment by cumajkeee** [comment] 2016-05-27 12:41
Thanks in advance

**Comment by Rcomian** [comment] 2016-05-28 07:44
Hi @cumajkeee,

It turns out this is a windows feature called **File System Tunneling**

If you delete a file and then create a new one with the same name within 15 seconds, the new file gets the creation date of the file just deleted. This works with *any* file created with *any* mechanism, so there isn't much we can do from within the logging system to adjust it.

See [this superuser post](http://superuser.com/questions/715536/wrong-date-created-for-files-in-windows-when-copying-files-if-the-file-has-alre)

The original [knowledgebase article](https://support.microsoft.com/en-us/kb/172190) contains details about how to adjust this timeout and turn it off - it's a registry setting.

Another workaround I can think of is to use [DateTime templating](https://www.npmjs.com/package/bunyan-rotating-file-stream#datetime-templating-y-m-d-h-m-s) to ensure that each file gets written with a new name. Your size thresholds should all work and the birthtime will be set correctly on each file created as each one will have a new name.

I'm going to close this issue as it's a windows feature and not something we have control over.
Please re-open if you can think of something that can fix it better.

**Closed by Rcomian** 2016-05-28 07:44 UTC

**Comment by cumajkeee** [comment] 2016-05-30 07:40
Thanks, I think I would implement workaround with templating.

**Comment by cumajkeee** [comment] 2016-06-01 11:20
@Rcomian, does module is responsible for creation initial log file on Win? Did all stuff with templating, but now have issue that on windows on first run, have ENOENT error no such file, even with startNewFile set tot 'true'.

**Comment by Rcomian** [comment] 2016-06-01 11:24
It should do everything to create the file, but not the folder.

Could add your logger configuration here and I'll look at it.

Cheers

**Comment by cumajkeee** [comment] 2016-06-01 11:40
```javascript
var LOG_DIR = path.join(app.getPath(USER_DIRECTORY), '/logs/');
var LOG_FILENAME = 'myapp%Y-%m-%dT%H:%M:%S.%LZ';
var LOG_SUFFIX = '.log';
var logFile = LOG_FILENAME + LOG_SUFFIX;

var config = {
        name: 'myApp',
        level: LOG_LEVEL.MAXIMUM.level,
        stream: new RotatingStream({
            path: LOG_DIR + logFile,
            threshold: LOG_MAX_FILE_SIZE, //1mb
            totalFiles: LOG_MAX_NUM_OF_FILES //5
        })
    };

var logger = bunyan.createLogger(config);
```

**Comment by cumajkeee** [comment] 2016-06-01 11:43
On Mac, as before work as expected, issue only on Windows

**Comment by Rcomian** [comment] 2016-06-01 12:00
Ah yes, I can see this erroring.

It's because you're building a filename with colons `':'` in it, which is a reserved character on windows.
If you remove the colons it should work.

(ps, I have no idea what `app.getPath` is, are you writing an electron app, perhaps?)

**Comment by Rcomian** [comment] 2016-06-01 12:11
I would also suggest removing the forward slashes around `'/logs/` - they are handled correctly by `path.join` in this instance, but it reads like it should be an error on windows.

**Comment by cumajkeee** [comment] 2016-06-01 12:54
Thanks a lot, works fine now, yeap it's an electron app :)
